// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb3tXh_1I3WS1_sAVrxeUxLZ_H7Lntdjk',
    appId: '1:1074912971738:web:6afa495b83d923a9b88ee3',
    messagingSenderId: '1074912971738',
    projectId: 'saglikliyasam-3603b',
    authDomain: 'saglikliyasam-3603b.firebaseapp.com',
    storageBucket: 'saglikliyasam-3603b.appspot.com',
    measurementId: 'G-XF2E8ZDDL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQd6DQNyu0Xr4zRu5RNPel02MhJMOvuKU',
    appId: '1:1074912971738:android:e6cea907bc880c1fb88ee3',
    messagingSenderId: '1074912971738',
    projectId: 'saglikliyasam-3603b',
    storageBucket: 'saglikliyasam-3603b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADxPB2rZaaLmbqWS-qY5w2NceC4QH-FjA',
    appId: '1:1074912971738:ios:1799b2b452d94ecab88ee3',
    messagingSenderId: '1074912971738',
    projectId: 'saglikliyasam-3603b',
    storageBucket: 'saglikliyasam-3603b.appspot.com',
    iosClientId: '1074912971738-b89nk52ri775ub65co6gle9i8d2rno09.apps.googleusercontent.com',
    iosBundleId: 'com.example.sagliksistem.sagliksistem',
  );
}
